name: Group4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - lime
  - pytorch
  - transformers=4.41.2
  - datasets
  - evaluate
  - nltk
  - accelerate=0.30.1
  - ipykernel
  - pip
  - jiwer
  - pip:
      - rouge_score
      - whisper
